### ISSUE TITLE
Lots of graphical issues and shader barely working on Linux

### ISSUE THREAD

**Issue by SpidFightFR** [BalintCsala/VanillaPuddingTart#14]
**Description of the bug**
When i load the shader, weird artifacts appear on screen, regardless of the version of the game (1.17 to 1.19.2) or the resource pack used. 

Water reflections don't work either for me. Unlike [on this video](https://youtu.be/F8NiTCxXhJU). 

**Resourcepack in use**
I use VNR.

**System information**
GPU: Nvidia GTX 1060 (Proprietary modules) - Driver: 520.56.06
CPU: AMD Ryzen 5 2600
OS: Archlinux up to date (zen kernel 6.0.9-1).

**Screenshots**
![2022-11-24_19 14 09](https://user-images.githubusercontent.com/60798703/203847173-ecbd8cbe-1335-4125-a6e6-43dc035659b3.png)
![2022-11-24_19 13 58](https://user-images.githubusercontent.com/60798703/203847176-b33f9cd0-93fe-481b-9d60-f451911da1cb.png)
![Screenshot_20221124_191417](https://user-images.githubusercontent.com/60798703/203847331-701ee7fc-10d9-47e5-a2d2-ab53ef6a96be.png)
![Screenshot_20221124_191429](https://user-images.githubusercontent.com/60798703/203847340-29a16345-11f5-49c8-8e2f-706b2c344c99.png)

**Logs**
[Logs](https://mclo.gs/w5rTahj)

**Additional notes**
I tried with different versions of Java, too. None of them worked either.

**Comment by BalintCsala** [comment]
Can you show a larger body of water? Hard to tell what could be going wrong from just two blocks

**Comment by SpidFightFR** [comment]
> Can you show a larger body of water? Hard to tell what could be going wrong from just two blocks

Hello, thanks for your quick answer.
There you go:

![2022-11-24_20 21 57](https://user-images.githubusercontent.com/60798703/203853396-ec8f3b90-3fef-4556-9149-8dcbd2559e80.png)
![2022-11-24_20 22 05](https://user-images.githubusercontent.com/60798703/203853408-e1a6f780-6499-4ba3-ac4f-ceb9586807bd.png)
![2022-11-24_20 22 15](https://user-images.githubusercontent.com/60798703/203853414-8cbd15a3-fc9f-496d-83a4-c5f5b935812a.png)


I hope this will help !

**Comment by BalintCsala** [comment]
Hm, try increasing render resolution back to 100%, I feel like that should solve it somewhat

**Comment by SpidFightFR** [comment]
> Hm, try increasing render resolution back to 100%, I feel like that should solve it somewhat

I also tried it, i loose a bit of performance, but the issues still happen…

Do you think that’s because to my gpu?

**Comment by BalintCsala** [comment]
Should be fixed in the latest release.
